-- MySQL Script generated by MySQL Workbench
-- Tue Sep 12 14:57:56 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BaseDatos
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `BaseDatos` ;

-- -----------------------------------------------------
-- Schema BaseDatos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BaseDatos` DEFAULT CHARACTER SET utf8 ;
USE `BaseDatos` ;

-- -----------------------------------------------------
-- Table `BaseDatos`.`Monitor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BaseDatos`.`Monitor` (
  `idMonitor` INT NOT NULL,
  `telefonoMonitor` VARCHAR(13) NOT NULL,
  `nacimientoMonitor` VARCHAR(10) NOT NULL,
  `direccionMonitor` VARCHAR(20) NOT NULL,
  `nombreMonitor` VARCHAR(50) NOT NULL,
  `correoMonitor` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idMonitor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BaseDatos`.`Instructor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BaseDatos`.`Instructor` (
  `idInstructor` INT NOT NULL,
  `nombreInstructor` VARCHAR(50) NOT NULL,
  `telefonoInstructor` VARCHAR(13) NOT NULL,
  `nacimientoInstructor` VARCHAR(10) NOT NULL,
  `direccionInstructor` VARCHAR(20) NOT NULL,
  `correoInstructor` VARCHAR(50) NOT NULL,
  `Monitor_idMonitor` INT NOT NULL,
  PRIMARY KEY (`idInstructor`),
  CONSTRAINT `fk_Instructor_Monitor`
    FOREIGN KEY (`Monitor_idMonitor`)
    REFERENCES `BaseDatos`.`Monitor` (`idMonitor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Instructor_Monitor_idx` ON `BaseDatos`.`Instructor` (`Monitor_idMonitor` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
