/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Usuario;
import java.awt.Color;
import java.awt.event.ActionListener;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Estudiantes
 */
public class GestionUsuario extends javax.swing.JFrame {

    /**
     * Creates new form Consulta
     */
    public GestionUsuario() {
        initComponents();
        panel = new JPanel();
        panel.setBackground(Color.blue);
        panel.setSize(600, 350);
        panel.setLocation(40, 80);
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
        //this.add(new JScrollPane(panel));
        this.add(panel);     
        refreshView();
    }
    
    public void initView(){
        this.setVisible(true);
    }
    
    public void closeView() {
        this.setVisible(false);
    }
    
    public void refreshView(){
        panel.repaint();
        panel.revalidate();
        pack();
    }
    
    public void setActionsCommands(){
        this.returnButton.setActionCommand("returnges");
    }
    
    public void addListeners(ActionListener objeto){
        this.returnButton.addActionListener(objeto);
    }
    
    
    public void showRegisters(Usuario[] usuarios, ActionListener objeto){
        panel.removeAll();
        for(int i = 0; i<usuarios.length; i++){
            JPanel mipanel = new JPanel();
            mipanel.setBackground(Color.LIGHT_GRAY);
            mipanel.setSize(Short.MAX_VALUE, 50);
            JLabel etiqueta = new JLabel(usuarios[i].getNombre());
            mipanel.add(etiqueta);
            JButton consultbutton = new JButton();
            consultbutton.setText("Consultar Info");
            consultbutton.setActionCommand("consult"+i);
            consultbutton.addActionListener(objeto);
            mipanel.add(consultbutton);
            JButton modifybutton = new JButton();
            modifybutton.setText("Modificar Info");
            modifybutton.setActionCommand("modify"+i);
            modifybutton.addActionListener(objeto);
            mipanel.add(modifybutton);
            JButton deletebutton = new JButton();
            deletebutton.setText("ELIMINAR");
            deletebutton.setActionCommand("delete"+i);
            deletebutton.addActionListener(objeto);
            mipanel.add(deletebutton); 
            panel.add(mipanel);
        }
        
        refreshView();
             
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        returnButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setBackground(new java.awt.Color(60, 100, 161));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("INTERFAZ DE CONSULTA");

        returnButton.setText("VOLVER");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(returnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(416, 416, 416)
                .addComponent(returnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_returnButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                //Codigo de prueba
                Usuario [] usuarios = new Usuario[20];
                for(int i = 0; i<usuarios.length; i++){
                    usuarios[i] = new Usuario(i,"User"+i,"13213131"+i,"03/10/2000"+i,"csrwer 34"+i,"erlewr@rer.com"+i);
                }
                GestionUsuario cons = new GestionUsuario();
                //cons.showRegisters(usuarios);
                cons.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton returnButton;
    // End of variables declaration//GEN-END:variables
    private JPanel panel;
}
